### ISSUE TITLE
Thrift2Eclipse does not work (NoClassDefFoundError)

### ISSUE THREAD

**Issue by bergmanngabor** [Taneb/ecore2thrift#14]
### Symptom

When executing the "Generate Thrift IDL" command, the following error message is shown:

> An internal error occurred during: "ecore2thrift".
> org/eclipse/epsilon/eol/execute/operations/OperationFactory

At the same time, this exception is logged at the Eclipse Error Log:

```
org.eclipse.core.jobs
Error
Fri Feb 12 04:20:00 PST 2016
An internal error occurred during: "ecore2thrift".

java.lang.NoClassDefFoundError: org/eclipse/epsilon/eol/execute/operations/OperationFactory
    at uk.ac.york.mondo.ecore2thrift.handlers.GenerateThriftCommand$1.run(GenerateThriftCommand.java:75)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.ClassNotFoundException: org.eclipse.epsilon.eol.execute.operations.OperationFactory cannot be found by org.eclipse.epsilon.evl.engine_1.2.0.201408251031
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
    at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 2 more
```
### How to reproduce

Grab a fresh Eclipse, install the latest Epsilon release (EMF Development tools) and ecore2thrift from the respective update sites. Check out [this project](https://github.com/mondo-project/mondo-integration/tree/master/uk.ac.york.mondo.integration.api) and try to generate the .thrift from [this file](https://github.com/mondo-project/mondo-integration/blob/master/uk.ac.york.mondo.integration.api/src/api.ecore).

**Comment by agarciadom** [comment]
I'm sorry that you're having issues with Ecore2Thrift. Please keep in mind after Nathan finished his internship, development is now taking place at my fork:

https://github.com/bluezio/ecore2thrift

This problem does not happen with the latest version of the above fork, since its update site is a composite site that automatically brings in all the required Epsilon components. I have followed these steps:
- Unzipped a fresh copy of the Eclipse Mars Modelling distribution.
- Installed the "Ecore2Thrift" feature from [this update site](http://bluezio.github.io/ecore2thrift/updates).
- Imported the mentioned project and generated the `.thrift` file from the mentioned `.ecore` file.
